import type { City } from "@/types/weather";

const ITALY_TIME_ZONE = "Europe/Rome";
const SOUTHERN_ENVY = "southern-envy";

export const CITIES = [
  {
    id: "agrigento",
    name: "Agrigento",
    latitude: 37.3111,
    longitude: 13.5765,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "alessandria",
    name: "Alessandria",
    latitude: 44.9073,
    longitude: 8.6117,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "ancona",
    name: "Ancona",
    latitude: 43.6158,
    longitude: 13.5189,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "andria",
    name: "Andria",
    latitude: 41.2318,
    longitude: 16.2917,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "aosta",
    name: "Aosta",
    latitude: 45.737,
    longitude: 7.3201,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "arezzo",
    name: "Arezzo",
    latitude: 43.4633,
    longitude: 11.8796,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "ascoli-piceno",
    name: "Ascoli Piceno",
    latitude: 42.8536,
    longitude: 13.5749,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "asti",
    name: "Asti",
    latitude: 44.9008,
    longitude: 8.2064,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "avellino",
    name: "Avellino",
    latitude: 40.9149,
    longitude: 14.791,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "bari",
    name: "Bari",
    latitude: 41.1171,
    longitude: 16.8719,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "barletta",
    name: "Barletta",
    latitude: 41.3197,
    longitude: 16.2837,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "belluno",
    name: "Belluno",
    latitude: 46.1425,
    longitude: 12.2167,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "benevento",
    name: "Benevento",
    latitude: 41.1298,
    longitude: 14.7826,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "bergamo",
    name: "Bergamo",
    latitude: 45.6983,
    longitude: 9.6773,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "biella",
    name: "Biella",
    latitude: 45.5629,
    longitude: 8.0583,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "bologna",
    name: "Bologna",
    latitude: 44.4949,
    longitude: 11.3426,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "bolzano",
    name: "Bolzano",
    latitude: 46.4983,
    longitude: 11.3548,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "brescia",
    name: "Brescia",
    latitude: 45.5416,
    longitude: 10.2118,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "brindisi",
    name: "Brindisi",
    latitude: 40.6327,
    longitude: 17.9418,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "cagliari",
    name: "Cagliari",
    latitude: 39.2238,
    longitude: 9.1217,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "caltanissetta",
    name: "Caltanissetta",
    latitude: 37.4901,
    longitude: 14.0629,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "campobasso",
    name: "Campobasso",
    latitude: 41.5603,
    longitude: 14.6627,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "carbonia",
    name: "Carbonia",
    latitude: 39.1672,
    longitude: 8.5222,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "caserta",
    name: "Caserta",
    latitude: 41.0723,
    longitude: 14.3311,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "catania",
    name: "Catania",
    latitude: 37.5079,
    longitude: 15.083,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "catanzaro",
    name: "Catanzaro",
    latitude: 38.9098,
    longitude: 16.5877,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "chieti",
    name: "Chieti",
    latitude: 42.3479,
    longitude: 14.1636,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "como",
    name: "Como",
    latitude: 45.8081,
    longitude: 9.0852,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "cosenza",
    name: "Cosenza",
    latitude: 39.2983,
    longitude: 16.2537,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "cremona",
    name: "Cremona",
    latitude: 45.1332,
    longitude: 10.0227,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "crotone",
    name: "Crotone",
    latitude: 39.0808,
    longitude: 17.1271,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "cuneo",
    name: "Cuneo",
    latitude: 44.3845,
    longitude: 7.5427,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "enna",
    name: "Enna",
    latitude: 37.5676,
    longitude: 14.2797,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "fermo",
    name: "Fermo",
    latitude: 43.1589,
    longitude: 13.7201,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "ferrara",
    name: "Ferrara",
    latitude: 44.8381,
    longitude: 11.6198,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "firenze",
    name: "Firenze",
    latitude: 43.7696,
    longitude: 11.2558,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "foggia",
    name: "Foggia",
    latitude: 41.4622,
    longitude: 15.5446,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "forli",
    name: "Forlì",
    latitude: 44.2227,
    longitude: 12.0407,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "frosinone",
    name: "Frosinone",
    latitude: 41.6396,
    longitude: 13.3422,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "genova",
    name: "Genova",
    latitude: 44.4056,
    longitude: 8.9463,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "gorizia",
    name: "Gorizia",
    latitude: 45.9415,
    longitude: 13.6215,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "grosseto",
    name: "Grosseto",
    latitude: 42.7635,
    longitude: 11.1124,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "imperia",
    name: "Imperia",
    latitude: 43.8897,
    longitude: 8.0395,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "isernia",
    name: "Isernia",
    latitude: 41.596,
    longitude: 14.2332,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "la-spezia",
    name: "La Spezia",
    latitude: 44.1025,
    longitude: 9.8241,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "laquila",
    name: "L’Aquila",
    latitude: 42.3498,
    longitude: 13.3995,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "latina",
    name: "Latina",
    latitude: 41.4676,
    longitude: 12.9037,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "lecce",
    name: "Lecce",
    latitude: 40.3515,
    longitude: 18.175,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "lecco",
    name: "Lecco",
    latitude: 45.8566,
    longitude: 9.3977,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "livorno",
    name: "Livorno",
    latitude: 43.5485,
    longitude: 10.3106,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "lodi",
    name: "Lodi",
    latitude: 45.3097,
    longitude: 9.5037,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "lucca",
    name: "Lucca",
    latitude: 43.8429,
    longitude: 10.5027,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "macerata",
    name: "Macerata",
    latitude: 43.2984,
    longitude: 13.4537,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "mantova",
    name: "Mantova",
    latitude: 45.1564,
    longitude: 10.7914,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "massa",
    name: "Massa",
    latitude: 44.0354,
    longitude: 10.1393,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "matera",
    name: "Matera",
    latitude: 40.6664,
    longitude: 16.6043,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "messina",
    name: "Messina",
    latitude: 38.1938,
    longitude: 15.554,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "milano",
    name: "Milano",
    latitude: 45.4642,
    longitude: 9.19,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "modena",
    name: "Modena",
    latitude: 44.6471,
    longitude: 10.9252,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "monza",
    name: "Monza",
    latitude: 45.5845,
    longitude: 9.2744,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "napoli",
    name: "Napoli",
    latitude: 40.8518,
    longitude: 14.2681,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "novara",
    name: "Novara",
    latitude: 45.4469,
    longitude: 8.6222,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "nuoro",
    name: "Nuoro",
    latitude: 40.3202,
    longitude: 9.3264,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "oristano",
    name: "Oristano",
    latitude: 39.9062,
    longitude: 8.5884,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "padova",
    name: "Padova",
    latitude: 45.4064,
    longitude: 11.8768,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "palermo",
    name: "Palermo",
    latitude: 38.1157,
    longitude: 13.3615,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "parma",
    name: "Parma",
    latitude: 44.8015,
    longitude: 10.3279,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "pavia",
    name: "Pavia",
    latitude: 45.1847,
    longitude: 9.1582,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "perugia",
    name: "Perugia",
    latitude: 43.1107,
    longitude: 12.3908,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "pesaro",
    name: "Pesaro",
    latitude: 43.9125,
    longitude: 12.9155,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "pescara",
    name: "Pescara",
    latitude: 42.4618,
    longitude: 14.2161,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "piacenza",
    name: "Piacenza",
    latitude: 45.0526,
    longitude: 9.6929,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "pisa",
    name: "Pisa",
    latitude: 43.7228,
    longitude: 10.4017,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "pistoia",
    name: "Pistoia",
    latitude: 43.9303,
    longitude: 10.9079,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "pordenone",
    name: "Pordenone",
    latitude: 45.9569,
    longitude: 12.6605,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "potenza",
    name: "Potenza",
    latitude: 40.6404,
    longitude: 15.8056,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "prato",
    name: "Prato",
    latitude: 43.8777,
    longitude: 11.1022,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "ragusa",
    name: "Ragusa",
    latitude: 36.9269,
    longitude: 14.7255,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "ravenna",
    name: "Ravenna",
    latitude: 44.4184,
    longitude: 12.2035,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "reggio-calabria",
    name: "Reggio Calabria",
    latitude: 38.1144,
    longitude: 15.65,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "reggio-emilia",
    name: "Reggio Emilia",
    latitude: 44.6983,
    longitude: 10.6301,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "rieti",
    name: "Rieti",
    latitude: 42.4045,
    longitude: 12.8567,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "rimini",
    name: "Rimini",
    latitude: 44.0678,
    longitude: 12.5695,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "roma",
    name: "Roma",
    latitude: 41.9028,
    longitude: 12.4964,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "rovigo",
    name: "Rovigo",
    latitude: 45.0698,
    longitude: 11.7902,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "salerno",
    name: "Salerno",
    latitude: 40.6824,
    longitude: 14.7681,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "sassari",
    name: "Sassari",
    latitude: 40.7259,
    longitude: 8.5557,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "savona",
    name: "Savona",
    latitude: 44.3091,
    longitude: 8.4772,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "siena",
    name: "Siena",
    latitude: 43.3188,
    longitude: 11.3308,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "siracusa",
    name: "Siracusa",
    latitude: 37.0755,
    longitude: 15.2866,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "sondrio",
    name: "Sondrio",
    latitude: 46.1699,
    longitude: 9.8788,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "taranto",
    name: "Taranto",
    latitude: 40.4644,
    longitude: 17.247,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "teramo",
    name: "Teramo",
    latitude: 42.6612,
    longitude: 13.699,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "terni",
    name: "Terni",
    latitude: 42.5636,
    longitude: 12.6427,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "torino",
    name: "Torino",
    latitude: 45.0703,
    longitude: 7.6869,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "trani",
    name: "Trani",
    latitude: 41.2775,
    longitude: 16.4101,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "trapani",
    name: "Trapani",
    latitude: 38.0176,
    longitude: 12.5362,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "trento",
    name: "Trento",
    latitude: 46.0748,
    longitude: 11.1217,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "treviso",
    name: "Treviso",
    latitude: 45.6669,
    longitude: 12.243,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "trieste",
    name: "Trieste",
    latitude: 45.6495,
    longitude: 13.7768,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "udine",
    name: "Udine",
    latitude: 46.0711,
    longitude: 13.2346,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "varese",
    name: "Varese",
    latitude: 45.8206,
    longitude: 8.8251,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "venezia",
    name: "Venezia",
    latitude: 45.4408,
    longitude: 12.3155,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "verbania",
    name: "Verbania",
    latitude: 45.9214,
    longitude: 8.5518,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "vercelli",
    name: "Vercelli",
    latitude: 45.3231,
    longitude: 8.4184,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "verona",
    name: "Verona",
    latitude: 45.4384,
    longitude: 10.9916,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "vibo-valentia",
    name: "Vibo Valentia",
    latitude: 38.6757,
    longitude: 16.098,
    timeZone: ITALY_TIME_ZONE,
    sunTone: SOUTHERN_ENVY,
  },
  {
    id: "vicenza",
    name: "Vicenza",
    latitude: 45.5455,
    longitude: 11.5354,
    timeZone: ITALY_TIME_ZONE,
  },
  {
    id: "viterbo",
    name: "Viterbo",
    latitude: 42.4207,
    longitude: 12.1077,
    timeZone: ITALY_TIME_ZONE,
  },
] as const satisfies readonly City[];

export const DEFAULT_CITY_ID = "bologna";

export type CityId = (typeof CITIES)[number]["id"];

export function getCityById(cityId: string | undefined): City {
  return CITIES.find((city) => city.id === cityId) ?? CITIES[0];
}
